import tailwindcssAnimate from 'tailwindcss-animate';
import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  safelist: [
    'animate-fade-in',
    'animate-float',
    'animate-glass-in',
    'animate-gold-particle-fall',
    'animate-scale-in',
    'animate-slide-right',
    'animate-slide-up',
    'dark',
    'field-input',
    'glass',
    'glass-button',
    'glass-card',
    'glass-dark',
    'glass-icon',
    'glass-input',
    'glass-nav',
    'glass-select',
    'glass-sidebar',
    'gradient-accent',
    'gradient-card',
    'gradient-hero',
    'gradient-primary',
    'page-enter',
    'shadow-accent',
    'shadow-card',
    'slide-in-from-top-full',
    'slide-out-to-top-full',
    'status-active',
    'status-available',
    'status-rented',
    'status-sold',
    'text-gradient',
    'text-muted-glass',
    'text-secondary-glass',
    'bg-gradient',
    'border-glass',
    'shadow-glass',
  ],
  content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        heading: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        glass: {
          DEFAULT: 'hsl(var(--glass))',
          border: 'hsl(var(--glass-border))',
          bg: 'hsl(var(--glass-bg))',
          'bg-hover': 'hsl(var(--glass-bg-hover))',
          'bg-active': 'hsl(var(--glass-bg-active))',
          highlight: 'hsl(var(--glass-highlight))',
          glow: 'hsl(var(--glass-glow))',
          'border-gold': 'var(--glass-border-gold)',
          'border-gold-strong': 'var(--glass-border-gold-strong)',
          shadow: 'var(--glass-shadow)',
          'shadow-hover': 'var(--glass-shadow-hover)',
          'shadow-gold': 'var(--glass-shadow-gold)',
          blur: 'var(--glass-blur)',
          'blur-heavy': 'var(--glass-blur-heavy)',
          'sidebar-bg': 'hsl(var(--sidebar-glass-bg))',
          'sidebar-border': 'hsl(var(--sidebar-glass-border))',
        },
        success: 'hsl(var(--success))',
        warning: 'hsl(var(--warning))',
        info: 'hsl(var(--info))',
        'gradient-start': 'hsl(var(--gradient-start))',
        'gradient-end': 'hsl(var(--gradient-end))',
        'glass-border': 'hsl(var(--glass-border))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      backgroundImage: {
        gradient:
          'linear-gradient(50deg, hsl(176deg 52% 6%) 0%, hsl(177deg 49% 7%) 12%, hsl(177deg 52% 8%) 24%, hsl(176deg 53% 9%) 37%, hsl(176deg 54% 10%) 50%, hsl(176deg 53% 9%) 63%, hsl(177deg 52% 8%) 76%, hsl(177deg 49% 7%) 88%, hsl(176deg 52% 6%) 100%)',
      },
      boxShadow: {
        glass: 'var(--glass-shadow)',
        'glass-hover': 'var(--glass-shadow-hover)',
        'glass-gold': 'var(--glass-shadow-gold)',
      },
      backdropBlur: {
        glass: 'var(--glass-blur)',
        'glass-heavy': 'var(--glass-blur-heavy)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in': {
          from: { opacity: '0', transform: 'translateX(-20px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-in': 'slide-in 0.3s ease-out',
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
